# Generated by Django 2.0.13 on 2019-04-16 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions_and_answers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userquestion',
            name='created_date',
            field=models.DateTimeField(null=True),
        ),
    ]
