# Generated by Django 2.0.13 on 2019-06-20 17:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('questions_and_answers', '0004_auto_20190619_1357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userquestion',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
