# Generated by Django 2.0.13 on 2019-06-20 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions_and_answers', '0006_respostas'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Respostas',
            new_name='Resposta',
        ),
    ]
