# Generated by Django 2.0.13 on 2019-04-18 18:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('quantidade_de_modulos', models.IntegerField()),
                ('turno', models.CharField(choices=[('mat', 'Matutino'), ('ves', 'Vespertino'), ('not', 'Noturno'), ('int', 'Integral')], default='Matutino', max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Professor', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='UnidadeCurricular',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('carga_horaria', models.IntegerField()),
                ('sala', models.CharField(max_length=50)),
                ('modulo_atual', models.IntegerField()),
                ('horario_de_inicio', models.TimeField()),
                ('horario_de_termino', models.TimeField()),
                ('fk_curso', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='timetable.Curso')),
                ('fk_professor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='timetable.Professor')),
            ],
        ),
        migrations.RemoveField(
            model_name='course',
            name='coordinator',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='fk_course',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='fk_teacher',
        ),
        migrations.DeleteModel(
            name='Course',
        ),
        migrations.DeleteModel(
            name='Subject',
        ),
        migrations.DeleteModel(
            name='Teacher',
        ),
        migrations.AddField(
            model_name='curso',
            name='coordenador',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='timetable.Professor'),
        ),
    ]
