# Generated by Django 2.0.13 on 2019-04-20 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0002_auto_20190418_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='coordenador',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
