# Generated by Django 2.0.13 on 2019-04-21 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0005_auto_20190421_1818'),
    ]

    operations = [
        migrations.RenameField(
            model_name='professor',
            old_name='Professor',
            new_name='nome',
        ),
    ]
